Adds pre-commit checks to the repo -- SGPROJ-1570
StratusGrid/terraform-aws-lambda-redis-slowlog-to-cw-logs pull request #7
Opened 2022-10-19 00:37 UTC by DJKaswa

## Change description

> Please review this and feel free to fix anything that will block it from passing on Github; otherwise it should be good to go as it passes all checks locally.

> Once you review and approve it, you can merge it to main (don’t forget to delete the branch). At that point, it’ll be ready to be moved to tf-auto.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [x] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

2022-10-19 08:59 UTC, JoseMotto-sg requested changes

2022-10-19 08:59 UTC, JoseMotto-sg commented on config.tf
> +#tfsec:ignore:aws-cloudwatch-log-group-customer-key -- Ignores warning on CMK encryption of CloudWatch Log Groups
Please create a KMS key for encrypting the resource
```suggestion
```

2022-10-19 08:59 UTC, JoseMotto-sg commented on examples/example1.tfnot
> +  subnet_ids          = ["subnet-fjf4b1b","subnet-fgtyuc1e"]
Use dummy names
```suggestion
  subnet_ids          = ["subnet-00000","subnet-00000"]
```

2022-10-19 08:59 UTC, JoseMotto-sg commented on examples/example1.tfnot
> +  security_group_ids  = ["sg-fjusg9d32"] # Needs to be able to reach all redis targets and internet via NAT GW
Use dummy names
```suggestion
  security_group_ids  = ["sg-00000"] # Needs to be able to reach all redis targets and internet via NAT GW
```

2022-10-19 08:59 UTC, JoseMotto-sg commented on examples/example2.tfnot
> +        "ip": "172.3.9.44",       <<< Client IP
Use dummy IPs
```suggestion
        "ip": "172.1.1.1",       <<< Client IP
```

2022-10-21 03:31 UTC, DJKaswa commented
@JoseMotto-sg please review again.

2022-10-21 10:44 UTC, JoseMotto-sg commented
Great Work!

2022-10-21 10:44 UTC, JoseMotto-sg approved these changes
LGTM

2022-10-25 15:12 UTC, merged